<a href="https://colab.research.google.com/github/strangelycutlemon/misc_code_challenges/blob/master/DS7_CC_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import ttest_ind
from scipy.stats import ttest_1samp
from scipy.stats import chisquare

from sklearn.datasets import load_iris
iris = load_iris()

In [0]:
# Saving our population data
population_data = iris.data

In [0]:
# Viewing our population data
population_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
# Google how to slice 2-D NumPy arrays
# Slice-out the entire first row (should return [5.1, 3.5, 1.4, 0.2])
print(population_data[0])

[5.1 3.5 1.4 0.2]


In [0]:
# Slice-out the first element in the first row (should return 5.1)
print(population_data[0, 0])

5.1


In [0]:
# Slice-out the third element in the first row (should return 1.4)
print(population_data[0,2])

1.4


In [0]:
# Slice-out the second element in the second row (should return 3.0)
print(population_data[1,1])

3.0


In [0]:
# Slice-out the second AND third elements in the third row (should return [3.2, 1.3])
print(population_data[2, 1:3])

[3.2 1.3]


In [0]:
# Slice-out the entire 5th row (should return [5. , 3.6, 1.4, 0.2])
print(population_data[4])

[5.  3.6 1.4 0.2]


In [0]:
# Slice-out the entire first column (should start off as [[5.1, 4.9, 4.7, 4.6, 5., 5.4, and so on...]])
print(population_data[:,0])

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [0]:
# Slice out the 4th through 6th elements in the first column (should return [4.6, 5., 5.4])
print(population_data[3:6,0:1])
john = population_data[3:6,0]
print(john[0])

john = population_data[3:6,0:1]
print(john[0])

[[4.6]
 [5. ]
 [5.4]]
4.6
[4.6]


In [0]:
# Look at the docs for np.mean() to see its parameters 
# Find the mean for each column in population_data and save it in the variable "population_means" (should return [[5.84333333, 3.05733333, 3.758     , 1.19933333]])
population_means = np.array([np.mean(col) for col in population_data.T])
population_means

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [0]:
# Find the mean for each row in population_data (should return [2.55 , 2.375, 2.35 , 2.35 , 2.55 , 2.85 , 2.425, 2.525, 2.225, and so on...])
row_means = np.array([np.mean(row) for row in population_data])
row_means
# I don't think this tells us much, because it's just averaging all variables for each observation

array([2.55 , 2.375, 2.35 , 2.35 , 2.55 , 2.85 , 2.425, 2.525, 2.225,
       2.4  , 2.7  , 2.5  , 2.325, 2.125, 2.8  , 3.   , 2.75 , 2.575,
       2.875, 2.675, 2.675, 2.675, 2.35 , 2.65 , 2.575, 2.45 , 2.6  ,
       2.6  , 2.55 , 2.425, 2.425, 2.675, 2.725, 2.825, 2.425, 2.4  ,
       2.625, 2.5  , 2.225, 2.55 , 2.525, 2.1  , 2.275, 2.675, 2.8  ,
       2.375, 2.675, 2.35 , 2.675, 2.475, 4.075, 3.9  , 4.1  , 3.275,
       3.85 , 3.575, 3.975, 2.9  , 3.85 , 3.3  , 2.875, 3.65 , 3.3  ,
       3.775, 3.35 , 3.9  , 3.65 , 3.4  , 3.6  , 3.275, 3.925, 3.55 ,
       3.8  , 3.7  , 3.725, 3.85 , 3.95 , 4.1  , 3.725, 3.2  , 3.2  ,
       3.15 , 3.4  , 3.85 , 3.6  , 3.875, 4.   , 3.575, 3.5  , 3.325,
       3.425, 3.775, 3.4  , 2.9  , 3.45 , 3.525, 3.525, 3.675, 2.925,
       3.475, 4.525, 3.875, 4.525, 4.15 , 4.375, 4.825, 3.4  , 4.575,
       4.2  , 4.85 , 4.2  , 4.075, 4.35 , 3.8  , 4.025, 4.3  , 4.2  ,
       5.1  , 4.875, 3.675, 4.525, 3.825, 4.8  , 3.925, 4.45 , 4.55 ,
       3.9  , 3.95 ,

In [0]:
# Google how to turn a 2-D numpy array into a 1-D array(there may be multiple ways)
# Use np.random.choice() to randomly select 10 elements in the first column (save this information as "sample_data")
'''
np.ravel() is what I would use, but I don't see how it relates to randomly selecting 10 elements
'''

sample_data = np.random.choice(population_data[:,0], size=10, replace=False)
sample_data

array([7.2, 5. , 5.1, 6.7, 5.7, 6.1, 4.4, 6.4, 6.1, 5.7])

In [0]:
# Find the mean of your sample_data
np.mean(sample_data)

5.840000000000001

In [0]:
# Now that you have a sample data and a known population mean, use the proper t-test to determine if the sample you drew has a statistically significant difference from the population mean

from scipy.stats import ttest_1samp

In [0]:
ttest_1samp(sample_data.ravel(), population_means[0]) 

Ttest_1sampResult(statistic=-0.012496095580100158, pvalue=0.9903024378054917)

# **No statistically significant difference from the population mean (sepal length)**

![Gaussian Distribution](https://www.get-digital-help.com/wp-content/uploads/2018/04/xHow-to-chart-a-bell-curve-normal-distribution1-1.png.pagespeed.ic.CAjYkbWOFB.png)

![T-Table](http://access-excel.tips/wp-content/uploads/2015/10/test-statistics-table.jpg)